services:
  - type: web
    name: salvageorganizer
    env: node
    buildCommand: npm install && npm run build
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
